const keywordsStrings = [
  "Almuda",
  "Almuda uz",
  "Accounting Uzbekistan",
  "Almuda Company",
  "almuda company",
  "buxgalteriya xizmatlari",
  "Financial Planning",
  "Accounting Services",
  "Tax Preparation",
  "Investment Management",
  "Retirement Planning",
  "Small Business Accounting",
  "Bookkeeping Services",
  "Tax Compliance",
  "Budgeting and Forecasting",
  "Financial Reporting",
  "Audit Services",
  "Estate Planning",
  "Personal Finance Tips",
  "Wealth Management",
  "Cryptocurrency Taxes",
  "Real Estate Accounting",
  "Financial Literacy",
  "IRS Regulations",
  "Financial Software",
  "Financial Education",
  "Business Valuation",
  "International Taxation",
  "Forensic Accounting",
  "Nonprofit Accounting",
  "Capital Gains Tax",
  "Financial Blogging",
  "Financial Advisor",
  "Fintech Trends",
  "Tax Deductions",
  "Credit Score Improvement",
  "Investment Strategies",
  "Student Loans and Finance",
  "Financial Calculators",
  "Cost Accounting",
  "Free company stamp",
  "Payroll Services",
  "Accounting Software Reviews",
  "Family Financial Planning",
  "Valid work permit",
  "Risk Management in Finance",
  'Start Business in the Uzbekistan','Business in the Uzbekistan', 'Register Business', 'Gather Information','Launch Business', 'Build Team in Business', 'accounting services online',
  "Opening bank account",
  "company registration",
  "accounting service",
  "accounting service help",
  "accounting service online",
  "accounting service organization",
  "Start Business",
  "accounting service cost",
  "accounting service contract",
  "accounting website",
  "accounting services for small business",
  "accounting problems"


];

const keywords = keywordsStrings.join(", ");

export { keywords };
